### ISSUE TITLE
Task "update active colour profiles" does not exist

### ISSUE THREAD

**Issue by darkymtp** [jtmzac/Auto-HDR-Colour-Profile-Switcher#1]
Hello.

The script try to start the task "update active colour profiles" :   
`Start-ScheduledTask -TaskName "update active colour profiles"`
but this task doesn't exist.

**Comment by jtmzac** [comment]
Sorry about that. Had it calling the wrong task from when I was testing something else.

I've fixed it now to call the correct task.

**Comment by darkymtp** [comment]
It works, thanks.
